language: go
sudo: true
go:
  - 1.9
services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_daf16889faa3_key -iv $encrypted_daf16889faa3_iv -in ./k8s/travis-ci.credentials.json.enc -out ./k8s/travis-ci.credentials.json -d
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci

deploy:
  - provider: script
    script: bin/build-image.sh && bin/push-image.sh && bin/deploy.sh
    on:
      branch: master