language: go
sudo: required
go:
  - 1.9
services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_daf16889faa3_key -iv $encrypted_daf16889faa3_iv -in ./k8s/travis-ci.credentials.json.enc -out ./k8s/travis-ci.credentials.json -d
  - openssl aes-256-cbc -K $encrypted_6009120a1dad_key -iv $encrypted_6009120a1dad_iv -in ./k8s/travis-ci.docker.password.enc -out ./k8s/travis-ci.docker.password -d
  - docker version
  - cat ./k8s/travis-ci.docker.password | docker login --username tourneytravisci --password-stdin
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci

deploy:
  - provider: script
    script: bin/build-image.sh && bin/push-image.sh && bin/deploy.sh
    on:
      branch: master