apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tourney
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: tourney
    spec:
      containers:
      - name: tourney
        image: andrewbackes/tourney:latest
        ports:
        - containerPort: 9090
        livenessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 10
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 10
          timeoutSeconds: 2