FROM ubuntu:trusty

RUN apt-get -y update && apt-get -y install curl
RUN echo "deb http://packages.cloud.google.com/apt cloud-sdk-trusty main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
RUN apt-get -y update && apt-get install -y google-cloud-sdk
RUN apt-get -y install kubectl